package com.jeremysu0818.caption.ui.theme

import androidx.compose.ui.graphics.Color

// Used only when Android's dynamic color is unavailable. Pixels continue to use
// the user's wallpaper-derived Material You palette by default.
val CaptionPrimaryLight = Color(0xFF006A6A)
val CaptionOnPrimaryLight = Color(0xFFFFFFFF)
val CaptionPrimaryContainerLight = Color(0xFF6FF7F6)
val CaptionOnPrimaryContainerLight = Color(0xFF002020)
val CaptionSecondaryLight = Color(0xFF4A6363)
val CaptionOnSecondaryLight = Color(0xFFFFFFFF)
val CaptionSecondaryContainerLight = Color(0xFFCDE8E7)
val CaptionOnSecondaryContainerLight = Color(0xFF051F1F)
val CaptionTertiaryLight = Color(0xFF4B607C)
val CaptionOnTertiaryLight = Color(0xFFFFFFFF)
val CaptionTertiaryContainerLight = Color(0xFFD3E4FF)
val CaptionOnTertiaryContainerLight = Color(0xFF041D36)
val CaptionBackgroundLight = Color(0xFFF7FBFA)
val CaptionOnBackgroundLight = Color(0xFF181C1C)
val CaptionSurfaceVariantLight = Color(0xFFDAE5E3)
val CaptionOnSurfaceVariantLight = Color(0xFF3F4948)
val CaptionOutlineLight = Color(0xFF6F7978)
val CaptionOutlineVariantLight = Color(0xFFBFC9C7)

val CaptionPrimaryDark = Color(0xFF4DDADA)
val CaptionOnPrimaryDark = Color(0xFF003737)
val CaptionPrimaryContainerDark = Color(0xFF004F4F)
val CaptionOnPrimaryContainerDark = Color(0xFF6FF7F6)
val CaptionSecondaryDark = Color(0xFFB1CCCB)
val CaptionOnSecondaryDark = Color(0xFF1C3534)
val CaptionSecondaryContainerDark = Color(0xFF334B4A)
val CaptionOnSecondaryContainerDark = Color(0xFFCDE8E7)
val CaptionTertiaryDark = Color(0xFFB3C8E8)
val CaptionOnTertiaryDark = Color(0xFF1C324B)
val CaptionTertiaryContainerDark = Color(0xFF334963)
val CaptionOnTertiaryContainerDark = Color(0xFFD3E4FF)
val CaptionBackgroundDark = Color(0xFF101414)
val CaptionOnBackgroundDark = Color(0xFFDFE3E2)
val CaptionSurfaceVariantDark = Color(0xFFBEC9C7)
val CaptionOnSurfaceVariantDark = Color(0xFF3F4948)
val CaptionOutlineDark = Color(0xFF899391)
val CaptionOutlineVariantDark = Color(0xFF3F4948)
