package com.jeremysu0818.voxline.ui.theme

import androidx.compose.ui.graphics.Color

// Used only when Android's dynamic color is unavailable or fixed theme is selected.
// Derived mathematically from Seed Color #056A60 using Material Design 3 Color Utilities.
val VoxlinePrimaryLight = Color(0xFF056A60)
val VoxlineOnPrimaryLight = Color(0xFFFFFFFF)
val VoxlinePrimaryContainerLight = Color(0xFF74F8E6)
val VoxlineOnPrimaryContainerLight = Color(0xFF00201C)
val VoxlineSecondaryLight = Color(0xFF4A635F)
val VoxlineOnSecondaryLight = Color(0xFFFFFFFF)
val VoxlineSecondaryContainerLight = Color(0xFFCCE8E2)
val VoxlineOnSecondaryContainerLight = Color(0xFF05201C)
val VoxlineTertiaryLight = Color(0xFF466179)
val VoxlineOnTertiaryLight = Color(0xFFFFFFFF)
val VoxlineTertiaryContainerLight = Color(0xFFCCE5FF)
val VoxlineOnTertiaryContainerLight = Color(0xFF001D31)
val VoxlineErrorLight = Color(0xFFBA1A1A)
val VoxlineOnErrorLight = Color(0xFFFFFFFF)
val VoxlineErrorContainerLight = Color(0xFFFFDAD6)
val VoxlineOnErrorContainerLight = Color(0xFF410002)
val VoxlineBackgroundLight = Color(0xFFF4FBF8)
val VoxlineOnBackgroundLight = Color(0xFF161D1C)
val VoxlineSurfaceVariantLight = Color(0xFFDAE5E1)
val VoxlineOnSurfaceVariantLight = Color(0xFF3F4947)
val VoxlineOutlineLight = Color(0xFF6F7977)
val VoxlineOutlineVariantLight = Color(0xFFBEC9C6)

val VoxlinePrimaryDark = Color(0xFF53DBCA)
val VoxlineOnPrimaryDark = Color(0xFF003731)
val VoxlinePrimaryContainerDark = Color(0xFF005048)
val VoxlineOnPrimaryContainerDark = Color(0xFF74F8E6)
val VoxlineSecondaryDark = Color(0xFFB1CCC6)
val VoxlineOnSecondaryDark = Color(0xFF1C3531)
val VoxlineSecondaryContainerDark = Color(0xFF334B47)
val VoxlineOnSecondaryContainerDark = Color(0xFFCCE8E2)
val VoxlineTertiaryDark = Color(0xFFADCAE6)
val VoxlineOnTertiaryDark = Color(0xFF153349)
val VoxlineTertiaryContainerDark = Color(0xFF2D4961)
val VoxlineOnTertiaryContainerDark = Color(0xFFCCE5FF)
val VoxlineErrorDark = Color(0xFFFFB4AB)
val VoxlineOnErrorDark = Color(0xFF690005)
val VoxlineErrorContainerDark = Color(0xFF93000A)
val VoxlineOnErrorContainerDark = Color(0xFFFFDAD6)
val VoxlineBackgroundDark = Color(0xFF0E1513)
val VoxlineOnBackgroundDark = Color(0xFFDDE4E1)
val VoxlineSurfaceVariantDark = Color(0xFF3F4947)
val VoxlineOnSurfaceVariantDark = Color(0xFFBEC9C6)
val VoxlineOutlineDark = Color(0xFF899390)
val VoxlineOutlineVariantDark = Color(0xFF3F4947)

